version: 2.1
jobs:
  build:
    docker:
      # image with node, npm and yarn installed
      - image: cimg/node:18.16.1
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD
    resource_class: xlarge
    steps:
      # checkout workspace to repo code
      - checkout

      # restore workspace if available
      # to skip re-installing node_modules
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      # install dependencies
      - run: yarn --ignore-engines --network-concurrency=1

      # save node_modules to cache
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # build code to production file
      - run:
          name: yarn build
          command: NODE_OPTIONS="--max_old_space_size=7168" yarn build --transpile-only

workflows:
  build:
    jobs:
      - build:
          context: org-switcheo
          filters:
            branches:
              only:
                - master
                - staging
